url: https://web-budget.github.io
baseurl: /site

# Site settings
title: webBudget
email: contato@arthurgregorio.eti.br
description: "Open source financial control"

# Team names, titles and social links
people:
- name: Arthur Gregório
  pic: 4
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/gregorioarthur
    - title: github
      url: https://github.com/arthurgregorio
    - title: linkedin
      url: https://www.linkedin.com/in/gregorioarthur/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/gregorioarthur
  - title: github
    url: http://github.com/web-budget
  - title: linkedin
    url: https://www.linkedin.com/in/gregorioarthur/

# Postal address (add as many lines as necessary)
address:
  - line: Foz do Iguaçu - Paraná
  - line: Brasil

# Build settings
markdown: kramdown
permalink: pretty